name: Compile LaTeX Resumes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: xu-cheng/texlive-action@v2
        with:
          texlive-version: '2023'
          texlive-scheme: 'medium'

      - name: Compile English Resume
        run: |
          pdflatex -interaction=nonstopmode -output-directory=./ resume_en.tex
          pdflatex -interaction=nonstopmode -output-directory=./ resume_en.tex # Run twice for proper references

      - name: Compile Spanish Resume
        run: |
          pdflatex -interaction=nonstopmode -output-directory=./ resume_es.tex
          pdflatex -interaction=nonstopmode -output-directory=./ resume_es.tex # Run twice for proper references

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resumes
          path: |
            resume_en.pdf
            resume_es.pdf
