name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX english
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume_en.tex
      - name: Compile LaTeX spanish
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume_es.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            resume_en.pdf
            resume_es.pdf
