name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX english
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume_en.tex

      - name: Upload English PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume_en.pdf  # Individual name for English PDF
          path: resume_en.pdf  # Single file

      - name: Compile LaTeX spanish
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume_es.tex

      - name: Upload Spanish PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume_es.pdf  # Individual name for Spanish PDF
          path: resume_es.pdf  # Single file
      - name: Commit PDFs
        run: |
          # Configure Git (name/email can be anything)
          git config --global user.name "PDF Updater Bot"
          git config --global user.email "pdf-bot@example.com"

          # Switch to the target branch (e.g., main or gh-pages)
          git checkout main

          # Add files explicitly (avoid wildcards)
          git add resume_en.pdf resume_es.pdf

          # Commit only if changes exist
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update PDFs [skip ci]"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          fi
      # - name: Prepare PDFs for GitHub Pages
      #   run: |
      #     mkdir -p docs  # Create a 'docs' folder
      #     cp *.pdf docs/ # Copy PDFs into it
      #
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs  # Publish the 'docs' folder
      #     keep_files: true     # Preserve existing files
