name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX english
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume_en.tex

      - name: Upload English PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume_en.pdf  # Individual name for English PDF
          path: resume_en.pdf  # Single file

      - name: Compile LaTeX spanish
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume_es.tex

      - name: Upload Spanish PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume_es.pdf  # Individual name for Spanish PDF
          path: resume_es.pdf  # Single file
      - name: Commit PDFs to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch
          git checkout main
          git add *.pdf
          git commit -m "Auto-generated PDFs [skip ci]"
          git push
